<a href="https://colab.research.google.com/github/ArjunJadhav-data/Airline-performance-revenue-analysis/blob/main/Airline_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
data=pd.read_csv('/content/PIA_2026_Advanced_Kaggle_Dataset.csv')

In [7]:
data[['Revenue_USD', 'Passengers', 'Ticket_Price_USD', 'Load_Factor_%']].corr()

                  Revenue_USD  Passengers  Ticket_Price_USD  Load_Factor_%
Revenue_USD          1.000000    0.727460          0.604237       0.249715
Passengers           0.727460    1.000000          0.022294       0.329220
Ticket_Price_USD     0.604237    0.022294          1.000000      -0.001940
Load_Factor_%        0.249715    0.329220         -0.001940       1.000000

In [8]:
data[['Passengers','Revenue_USD']].mean()

Passengers        143.27750
Revenue_USD    115149.45875
dtype: float64

Which flights are generating highest and lowest revenue?

In [9]:
data[['Flight_ID','Revenue_USD']].max()

Flight_ID      PK2026_0800
Revenue_USD         494654
dtype: object

In [10]:
data[['Flight_ID','Revenue_USD']].min()

Flight_ID      PK2026_0001
Revenue_USD           4712
dtype: object

4 . Is there any relationship between ticket price and revenue?

In [11]:
data[['Ticket_Price_USD','Revenue_USD']].corr()

                  Ticket_Price_USD  Revenue_USD
Ticket_Price_USD          1.000000     0.604237
Revenue_USD               0.604237     1.000000


5 .
Which range of ticket prices gives maximum profit?

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Flight_ID                800 non-null    object
 1   Date                     800 non-null    object
 2   Month                    800 non-null    object
 3   Day_of_Week              800 non-null    object
 4   Departure_City           800 non-null    object
 5   Arrival_City             800 non-null    object
 6   Route_Type               800 non-null    object
 7   Aircraft_Type            800 non-null    object
 8   Flight_Duration_Minutes  800 non-null    int64
 9   Passengers               800 non-null    int64
 10  Seat_Capacity            800 non-null    int64
 11  Load_Factor_%            800 non-null    float64
 12  Ticket_Price_USD         800 non-null    int64
 13  Revenue_USD              800 non-null    int64
 14  Delay_Minutes            800 non-null    int64
 15  Unnamed: 15              1 non-null      float64
 16  Delay_Category           800 non-null    object
 17  On_Time_Status           800 non-null    object
 18  Weather_Condition        800 non-null    object
 19  Fuel_Consumption_Liters  800 non-null    int64
 20  CO2_Emissions_kg         800 non-null    float64
 21  Customer_Rating          800 non-null    float64
 22  Customer_Feedback        800 non-null    object
dtypes: float64(4), int64(7), object(12)
memory usage: 143.9+ KB

In [17]:
data = data.drop('Unnamed: 15', axis=1)

remove umwanted data from your table

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Flight_ID                800 non-null    object
 1   Date                     800 non-null    object
 2   Month                    800 non-null    object
 3   Day_of_Week              800 non-null    object
 4   Departure_City           800 non-null    object
 5   Arrival_City             800 non-null    object
 6   Route_Type               800 non-null    object
 7   Aircraft_Type            800 non-null    object
 8   Flight_Duration_Minutes  800 non-null    int64
 9   Passengers               800 non-null    int64
 10  Seat_Capacity            800 non-null    int64
 11  Load_Factor_%            800 non-null    float64
 12  Ticket_Price_USD         800 non-null    int64
 13  Revenue_USD              800 non-null    int64
 14  Delay_Minutes            800 non-null    int64
 15  Delay_Category           800 non-null    object
 16  On_Time_Status           800 non-null    object
 17  Weather_Condition        800 non-null    object
 18  Fuel_Consumption_Liters  800 non-null    int64
 19  CO2_Emissions_kg         800 non-null    float64
 20  Customer_Rating          800 non-null    float64
 21  Customer_Feedback        800 non-null    object
dtypes: float64(3), int64(7), object(12)
memory usage: 137.6+ KB