<a href="https://colab.research.google.com/github/ArjunJadhav-data/Airline-performance-revenue-analysis/blob/main/dataCleanigAndReplaceValues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from google.colab import files

In [4]:
p=pd.read_excel('/content/data.xlsx',header=2)
p

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96,16729.92,96.0,16729.92,NaN,NaN,NaN,NaN
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19608,1072181.83,10908.0,682678.51,8700.0,389503.32,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16320,409870.56,NaN,NaN,16320.0,409870.56,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN
109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10848,324300.96,NaN,NaN,10848.0,324300.96,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,326536,16183034.84,115164.0,7237241.37,211372.0,8945793.47,NaN,NaN

In [5]:
p.dropna(subset=['SNO.'])

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
5,4.0,1. PP/HO/MOTHER WH,03/04/2026,PI0113,03/04/2026,SOW 10233,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,10/04/2026,SL-275,3840,168696.96,2688.0,146993.28,1152.0,21703.68,19170056817,10/04/2026
6,5.0,1. PP/HO/MOTHER WH,03/04/2026,OOSPI0113,03/04/2026,SOW 10234,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,NaN,NaN,5376,150126.72,NaN,NaN,5376.0,150126.72,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,66.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10877,4S MARKETING -JABALPUR,NaN,NaN,8640,244540.80,NaN,NaN,8640.0,244540.80,NaN,NaN
104,67.0,1. PP/HO/MOTHER WH,17/04/2026,PI0164,17/04/2026,SOW 10878,SUPER CASHEW -KOLHAPUR,NaN,NaN,2928,89309.76,NaN,NaN,2928.0,89309.76,NaN,NaN
105,68.0,1. PP/HO/MOTHER WH,17/04/2026,OOSPI0164,17/04/2026,SOW 10879,SUPER CASHEW -KOLHAPUR,NaN,NaN,13392,320560.80,NaN,NaN,13392.0,320560.80,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN

In [10]:
p['PARTY ORDER NO.']=p['PARTY ORDER NO.'].str.replace(r'oos\d+','oos',regex=True)
p

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96,16729.92,96.0,16729.92,NaN,NaN,NaN,NaN
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19608,1072181.83,10908.0,682678.51,8700.0,389503.32,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16320,409870.56,NaN,NaN,16320.0,409870.56,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN
109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10848,324300.96,NaN,NaN,10848.0,324300.96,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,326536,16183034.84,115164.0,7237241.37,211372.0,8945793.47,NaN,NaN

In [8]:
p

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96,16729.92,96.0,16729.92,NaN,NaN,NaN,NaN
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19608,1072181.83,10908.0,682678.51,8700.0,389503.32,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16320,409870.56,NaN,NaN,16320.0,409870.56,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN
109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10848,324300.96,NaN,NaN,10848.0,324300.96,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,326536,16183034.84,115164.0,7237241.37,211372.0,8945793.47,NaN,NaN

In [11]:
p=p.dropna(subset=['SNO.'])
p

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
5,4.0,1. PP/HO/MOTHER WH,03/04/2026,PI0113,03/04/2026,SOW 10233,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,10/04/2026,SL-275,3840,168696.96,2688.0,146993.28,1152.0,21703.68,19170056817,10/04/2026
6,5.0,1. PP/HO/MOTHER WH,03/04/2026,OOSPI0113,03/04/2026,SOW 10234,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,NaN,NaN,5376,150126.72,NaN,NaN,5376.0,150126.72,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,66.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10877,4S MARKETING -JABALPUR,NaN,NaN,8640,244540.80,NaN,NaN,8640.0,244540.80,NaN,NaN
104,67.0,1. PP/HO/MOTHER WH,17/04/2026,PI0164,17/04/2026,SOW 10878,SUPER CASHEW -KOLHAPUR,NaN,NaN,2928,89309.76,NaN,NaN,2928.0,89309.76,NaN,NaN
105,68.0,1. PP/HO/MOTHER WH,17/04/2026,OOSPI0164,17/04/2026,SOW 10879,SUPER CASHEW -KOLHAPUR,NaN,NaN,13392,320560.80,NaN,NaN,13392.0,320560.80,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN

In [14]:
p.loc[:,'PARTY ORDER NO.']=p['PARTY ORDER NO.'].str.replace(r'oos\d+','oos',regex=True)

In [15]:
p

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
5,4.0,1. PP/HO/MOTHER WH,03/04/2026,PI0113,03/04/2026,SOW 10233,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,10/04/2026,SL-275,3840,168696.96,2688.0,146993.28,1152.0,21703.68,19170056817,10/04/2026
6,5.0,1. PP/HO/MOTHER WH,03/04/2026,OOSPI0113,03/04/2026,SOW 10234,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,NaN,NaN,5376,150126.72,NaN,NaN,5376.0,150126.72,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,66.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10877,4S MARKETING -JABALPUR,NaN,NaN,8640,244540.80,NaN,NaN,8640.0,244540.80,NaN,NaN
104,67.0,1. PP/HO/MOTHER WH,17/04/2026,PI0164,17/04/2026,SOW 10878,SUPER CASHEW -KOLHAPUR,NaN,NaN,2928,89309.76,NaN,NaN,2928.0,89309.76,NaN,NaN
105,68.0,1. PP/HO/MOTHER WH,17/04/2026,OOSPI0164,17/04/2026,SOW 10879,SUPER CASHEW -KOLHAPUR,NaN,NaN,13392,320560.80,NaN,NaN,13392.0,320560.80,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN

In [16]:
p.loc[:,'PARTY ORDER NO.']=p['PARTY ORDER NO.'].str.replace(r'(?i)oos.*','oos',regex=True)
p

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,oos,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
5,4.0,1. PP/HO/MOTHER WH,03/04/2026,PI0113,03/04/2026,SOW 10233,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,10/04/2026,SL-275,3840,168696.96,2688.0,146993.28,1152.0,21703.68,19170056817,10/04/2026
6,5.0,1. PP/HO/MOTHER WH,03/04/2026,oos,03/04/2026,SOW 10234,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,NaN,NaN,5376,150126.72,NaN,NaN,5376.0,150126.72,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,66.0,1. PP/HO/MOTHER WH,17/04/2026,oos,17/04/2026,SOW 10877,4S MARKETING -JABALPUR,NaN,NaN,8640,244540.80,NaN,NaN,8640.0,244540.80,NaN,NaN
104,67.0,1. PP/HO/MOTHER WH,17/04/2026,PI0164,17/04/2026,SOW 10878,SUPER CASHEW -KOLHAPUR,NaN,NaN,2928,89309.76,NaN,NaN,2928.0,89309.76,NaN,NaN
105,68.0,1. PP/HO/MOTHER WH,17/04/2026,oos,17/04/2026,SOW 10879,SUPER CASHEW -KOLHAPUR,NaN,NaN,13392,320560.80,NaN,NaN,13392.0,320560.80,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oos,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN

In [21]:
p.to_excel('file.xlsx', index=False)

In [22]:
files.download('file.xlsx')