<a href="https://colab.research.google.com/github/ArjunJadhav-data/Airline-performance-revenue-analysis/blob/main/dataCleanigAndReplaceValues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from google.colab import files

In [3]:
p=pd.read_excel('/content/b17be5f915f54892956d661872c0a6a7.xlsx',header=2)
p

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96,16729.92,96.0,16729.92,NaN,NaN,NaN,NaN
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19608,1072181.83,10908.0,682678.51,8700.0,389503.32,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15312,580191.36,NaN,NaN,15312.0,580191.36,NaN,NaN
148,97.0,1. PP/HO/MOTHER WH,18/04/2026,PI0173,18/04/2026,SOW 10967,RADHA KRISHNAN ENTERPRISES -AMBALA,NaN,NaN,4572,346997.40,NaN,NaN,4572.0,346997.40,NaN,NaN
149,98.0,1. PP/HO/MOTHER WH,18/04/2026,OOSPI0173,18/04/2026,SOW 10968,RADHA KRISHNAN ENTERPRISES -AMBALA,NaN,NaN,960,101958.72,NaN,NaN,960.0,101958.72,NaN,NaN
150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5532,448956.12,NaN,NaN,5532.0,448956.12,NaN,NaN
151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,456831,22437887.67,156259.0,10675618.12,300572.0,11762269.55,NaN,NaN

In [4]:
p.dropna(subset=['SNO.'])

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
5,4.0,1. PP/HO/MOTHER WH,03/04/2026,PI0113,03/04/2026,SOW 10233,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,10/04/2026,SL-275,3840,168696.96,2688.0,146993.28,1152.0,21703.68,19170056817,10/04/2026
6,5.0,1. PP/HO/MOTHER WH,03/04/2026,OOSPI0113,03/04/2026,SOW 10234,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,NaN,NaN,5376,150126.72,NaN,NaN,5376.0,150126.72,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,94.0,1. PP/HO/MOTHER WH,18/04/2026,PI0171,18/04/2026,SOW 10954,RANKSON ASSOCIATES -JAMMU,18/04/2026,SL-634,1536,117660.00,1536.0,117660.00,NaN,NaN,,NaN
145,95.0,1. PP/HO/MOTHER WH,18/04/2026,PI0172,18/04/2026,SOW 10965,INDIAN SALES -RAIPUR,NaN,NaN,8016,412744.32,NaN,NaN,8016.0,412744.32,NaN,NaN
146,96.0,1. PP/HO/MOTHER WH,18/04/2026,OOSPI0172,18/04/2026,SOW 10966,INDIAN SALES -RAIPUR,NaN,NaN,7296,167447.04,NaN,NaN,7296.0,167447.04,NaN,NaN
148,97.0,1. PP/HO/MOTHER WH,18/04/2026,PI0173,18/04/2026,SOW 10967,RADHA KRISHNAN ENTERPRISES -AMBALA,NaN,NaN,4572,346997.40,NaN,NaN,4572.0,346997.40,NaN,NaN
149,98.0,1. PP/HO/MOTHER WH,18/04/2026,OOSPI0173,18/04/2026,SOW 10968,RADHA KRISHNAN ENTERPRISES -AMBALA,NaN,NaN,960,101958.72,NaN,NaN,960.0,101958.72,NaN,NaN

In [5]:
p['PARTY ORDER NO.']=p['PARTY ORDER NO.'].str.replace(r'(?i)oos.*','oos',regex=True)

In [6]:
p=p.dropna(subset=['SNO.'])

In [7]:
p.to_excel('file.xlsx', index=False)

In [8]:
files.download('file.xlsx')