<a href="https://colab.research.google.com/github/ArjunJadhav-data/Airline-performance-revenue-analysis/blob/main/Order%20vs%20sale.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from ast import AST
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
pf=pd.read_excel('/content/data.xlsx',header=2)

In [10]:
pf

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96,16729.92,96.0,16729.92,NaN,NaN,NaN,NaN
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19608,1072181.83,10908.0,682678.51,8700.0,389503.32,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16320,409870.56,NaN,NaN,16320.0,409870.56,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN
109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10848,324300.96,NaN,NaN,10848.0,324300.96,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,326536,16183034.84,115164.0,7237241.37,211372.0,8945793.47,NaN,NaN

In [15]:
pf

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96,16729.92,96.0,16729.92,NaN,NaN,NaN,NaN
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19608,1072181.83,10908.0,682678.51,8700.0,389503.32,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16320,409870.56,NaN,NaN,16320.0,409870.56,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN
109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10848,324300.96,NaN,NaN,10848.0,324300.96,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,326536,16183034.84,115164.0,7237241.37,211372.0,8945793.47,NaN,NaN

In [20]:
pf['SNO.'].isna()

0      False
1       True
2      False
3      False
4       True
       ...
106     True
107    False
108    False
109     True
110     True
Name: SNO., Length: 111, dtype: bool

In [36]:
pf['SNO.'].dropna(how='all')

0       1.0
2       2.0
3       3.0
5       4.0
6       5.0
       ...
102    66.0
104    67.0
105    68.0
107    69.0
108    70.0
Name: SNO., Length: 70, dtype: float64

In [37]:
pf

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96,16729.92,96.0,16729.92,NaN,NaN,NaN,NaN
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19608,1072181.83,10908.0,682678.51,8700.0,389503.32,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16320,409870.56,NaN,NaN,16320.0,409870.56,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN
109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10848,324300.96,NaN,NaN,10848.0,324300.96,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,326536,16183034.84,115164.0,7237241.37,211372.0,8945793.47,NaN,NaN

In [38]:
pf['SNO.'].isna().sum()

np.int64(41)

In [30]:

pf['SNO.'].dropna()

0       1.0
2       2.0
3       3.0
5       4.0
6       5.0
       ...
102    66.0
104    67.0
105    68.0
107    69.0
108    70.0
Name: SNO., Length: 70, dtype: float64

In [31]:
pf

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96,16729.92,96.0,16729.92,NaN,NaN,NaN,NaN
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19608,1072181.83,10908.0,682678.51,8700.0,389503.32,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16320,409870.56,NaN,NaN,16320.0,409870.56,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN
109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10848,324300.96,NaN,NaN,10848.0,324300.96,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,326536,16183034.84,115164.0,7237241.37,211372.0,8945793.47,NaN,NaN

In [32]:
pf.to_csv('cleaned_data.csv', index=False)

In [35]:
from google.colab import files
files.download('cleaned_data.csv')

In [33]:
pf

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96,16729.92,96.0,16729.92,NaN,NaN,NaN,NaN
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19608,1072181.83,10908.0,682678.51,8700.0,389503.32,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16320,409870.56,NaN,NaN,16320.0,409870.56,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN
109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10848,324300.96,NaN,NaN,10848.0,324300.96,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,326536,16183034.84,115164.0,7237241.37,211372.0,8945793.47,NaN,NaN

In [40]:
pfata=pf.dropna(subset=['SNO.'])

In [41]:
pfata

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
5,4.0,1. PP/HO/MOTHER WH,03/04/2026,PI0113,03/04/2026,SOW 10233,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,10/04/2026,SL-275,3840,168696.96,2688.0,146993.28,1152.0,21703.68,19170056817,10/04/2026
6,5.0,1. PP/HO/MOTHER WH,03/04/2026,OOSPI0113,03/04/2026,SOW 10234,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,NaN,NaN,5376,150126.72,NaN,NaN,5376.0,150126.72,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,66.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10877,4S MARKETING -JABALPUR,NaN,NaN,8640,244540.80,NaN,NaN,8640.0,244540.80,NaN,NaN
104,67.0,1. PP/HO/MOTHER WH,17/04/2026,PI0164,17/04/2026,SOW 10878,SUPER CASHEW -KOLHAPUR,NaN,NaN,2928,89309.76,NaN,NaN,2928.0,89309.76,NaN,NaN
105,68.0,1. PP/HO/MOTHER WH,17/04/2026,OOSPI0164,17/04/2026,SOW 10879,SUPER CASHEW -KOLHAPUR,NaN,NaN,13392,320560.80,NaN,NaN,13392.0,320560.80,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN

In [47]:
pfata.to_csv('cleaned_data1.csv', index=False)

In [48]:
from google.colab import files
files.download('cleaned_data1.csv')

In [49]:
pfata

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
5,4.0,1. PP/HO/MOTHER WH,03/04/2026,PI0113,03/04/2026,SOW 10233,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,10/04/2026,SL-275,3840,168696.96,2688.0,146993.28,1152.0,21703.68,19170056817,10/04/2026
6,5.0,1. PP/HO/MOTHER WH,03/04/2026,OOSPI0113,03/04/2026,SOW 10234,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,NaN,NaN,5376,150126.72,NaN,NaN,5376.0,150126.72,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,66.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10877,4S MARKETING -JABALPUR,NaN,NaN,8640,244540.80,NaN,NaN,8640.0,244540.80,NaN,NaN
104,67.0,1. PP/HO/MOTHER WH,17/04/2026,PI0164,17/04/2026,SOW 10878,SUPER CASHEW -KOLHAPUR,NaN,NaN,2928,89309.76,NaN,NaN,2928.0,89309.76,NaN,NaN
105,68.0,1. PP/HO/MOTHER WH,17/04/2026,OOSPI0164,17/04/2026,SOW 10879,SUPER CASHEW -KOLHAPUR,NaN,NaN,13392,320560.80,NaN,NaN,13392.0,320560.80,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN

In [50]:
p=pfata

In [51]:
p

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
5,4.0,1. PP/HO/MOTHER WH,03/04/2026,PI0113,03/04/2026,SOW 10233,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,10/04/2026,SL-275,3840,168696.96,2688.0,146993.28,1152.0,21703.68,19170056817,10/04/2026
6,5.0,1. PP/HO/MOTHER WH,03/04/2026,OOSPI0113,03/04/2026,SOW 10234,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,NaN,NaN,5376,150126.72,NaN,NaN,5376.0,150126.72,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,66.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10877,4S MARKETING -JABALPUR,NaN,NaN,8640,244540.80,NaN,NaN,8640.0,244540.80,NaN,NaN
104,67.0,1. PP/HO/MOTHER WH,17/04/2026,PI0164,17/04/2026,SOW 10878,SUPER CASHEW -KOLHAPUR,NaN,NaN,2928,89309.76,NaN,NaN,2928.0,89309.76,NaN,NaN
105,68.0,1. PP/HO/MOTHER WH,17/04/2026,OOSPI0164,17/04/2026,SOW 10879,SUPER CASHEW -KOLHAPUR,NaN,NaN,13392,320560.80,NaN,NaN,13392.0,320560.80,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN

In [52]:
p['PARTY ORDER NO.']

0
2          PI012
3      OOSPI0112
5         PI0113
6      OOSPI0113
         ...
102    oosPI0163
104       PI0164
105    OOSPI0164
107       PI0163
108    oosPI0163
Name: PARTY ORDER NO., Length: 70, dtype: object

In [53]:
p['PARTY ORDER NO.']=p['PARTY ORDER NO.'].str.replace(r'oos\d+','oos',regex=True)

/tmp/ipykernel_802/1992474282.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p['PARTY ORDER NO.']=p['PARTY ORDER NO.'].str.replace(r'oos\d+','oos',regex=True)

In [54]:
p

,SNO.,BRANCH NAME,PARTY ORDER DATE,PARTY ORDER NO.,ORDER DATE,ORDER NO.,PARTY NAME,SALE DOCUMENT DATE,SALE DOCUMENT NO,ORDERED QTY,ORD.AMT.,DISP QTY,DISP AMOUNT,PENDING QTY,PENDI.AMT.,G.R. NUMBER,G.R. DATE
0,1.0,1. PP/HO/MOTHER WH,02/04/2026,,02/04/2026,SOW 10227,SHIVANI TRADERS -PURI,02/04/2026,SL-20,96,16729.92,96.0,16729.92,NaN,NaN,4313122,03/04/2026
2,2.0,1. PP/HO/MOTHER WH,02/04/2026,PI012,02/04/2026,SOW 10230,R K & SONS -LUDHIANA,07/04/2026,SL-180,12636,715234.03,10908.0,682678.51,1728.0,32555.52,65275,07/04/2026
3,3.0,1. PP/HO/MOTHER WH,02/04/2026,OOSPI0112,02/04/2026,SOW 10231,R K & SONS -LUDHIANA,NaN,NaN,6972,356947.80,NaN,NaN,6972.0,356947.80,NaN,NaN
5,4.0,1. PP/HO/MOTHER WH,03/04/2026,PI0113,03/04/2026,SOW 10233,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,10/04/2026,SL-275,3840,168696.96,2688.0,146993.28,1152.0,21703.68,19170056817,10/04/2026
6,5.0,1. PP/HO/MOTHER WH,03/04/2026,OOSPI0113,03/04/2026,SOW 10234,JAISWAL ENTERPRISES -SAMBHAJI NAGAR,NaN,NaN,5376,150126.72,NaN,NaN,5376.0,150126.72,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,66.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10877,4S MARKETING -JABALPUR,NaN,NaN,8640,244540.80,NaN,NaN,8640.0,244540.80,NaN,NaN
104,67.0,1. PP/HO/MOTHER WH,17/04/2026,PI0164,17/04/2026,SOW 10878,SUPER CASHEW -KOLHAPUR,NaN,NaN,2928,89309.76,NaN,NaN,2928.0,89309.76,NaN,NaN
105,68.0,1. PP/HO/MOTHER WH,17/04/2026,OOSPI0164,17/04/2026,SOW 10879,SUPER CASHEW -KOLHAPUR,NaN,NaN,13392,320560.80,NaN,NaN,13392.0,320560.80,NaN,NaN
107,69.0,1. PP/HO/MOTHER WH,17/04/2026,PI0163,17/04/2026,SOW 10881,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,3744,154196.64,NaN,NaN,3744.0,154196.64,NaN,NaN
108,70.0,1. PP/HO/MOTHER WH,17/04/2026,oosPI0163,17/04/2026,SOW 10882,ABC THE BUSINESS PEOPLE -SOLAPUR,NaN,NaN,7104,170104.32,NaN,NaN,7104.0,170104.32,NaN,NaN